version: '3.4'
services:
  php:
    image: yiisoftware/yii-php:7.4-apache
    working_dir: /app
    volumes:
      - .:/app
      # For composer usage in container; NOTE! There may be performance issues, see also https://github.com/docker/for-mac/issues/77
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
    ports:
      - '30080:80'
