version: '3.4'
services:
  php:
    volumes:
      # For composer usage in container; NOTE! There may be performance issues, see also https://github.com/docker/for-mac/issues/77
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      # mount ssh keys
      - ~/.ssh:/app/docker/home/.ssh:ro
    ports:
      - '30080:80'
