#!/usr/bin/env php
<?php

use Yiisoft\YiiDevTool\App\Component\Console\YiiDevToolApplication;

require __DIR__ . '/vendor/autoload.php';

(new YiiDevToolApplication())
    ->setRootDir(__DIR__)
    ->run();
