#!/usr/bin/env php
<?php

use Yiisoft\YiiDevTool\App\YiiDevToolApplication;

require __DIR__ . '/vendor/autoload.php';

$configFile = __DIR__ . '/config/config.local.php';
$config = [];
if (file_exists($configFile)) {
    $config = require $configFile;
}

(new YiiDevToolApplication($config))
    ->setRootDir(__DIR__)
    ->run();
