on:
  pull_request:
    paths-ignore:
      - 'docs/**'
      - 'README.md'
      - 'CHANGELOG.md'
      - '.gitignore'
      - '.gitattributes'
      - 'infection.json.dist'
      - 'psalm.xml'

  push:
    branches:
      - master
    paths-ignore:
      - 'docs/**'
      - 'README.md'
      - 'CHANGELOG.md'
      - '.gitignore'
      - '.gitattributes'
      - 'infection.json.dist'
      - 'psalm.xml'

name: build

jobs:
  phpunit:
    uses: yiisoft/actions/.github/workflows/phpunit.yml@master
    with:
      os: >-
        ['ubuntu-latest']
      php: >-
        ['8.0']
      composer-command: composer update --prefer-dist --no-interaction --no-progress --optimize-autoloader --ansi --no-security-blocking
